[package]
name = "ws-app"
version = "0.1.0"
edition = "2021"

[dependencies]
actix = "0.13.5"
actix-cors = "0.7.0"
actix-web = "4.7.0"
actix-web-actors = "4.3.0"
serde = {version = "1.0.203", features = ["derive"]}
